tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "alacritty"
brew "bash-completion@2"
brew "cmake"
brew "curl"
brew "exa"
brew "flux"
brew "fzf"
brew "git"
brew "git-crypt"
brew "gnupg"
brew "go"
brew "htop"
brew "hyperfine"
brew "jq"
brew "mas"
brew "mkvtoolnix"
brew "monodraw"
brew "moreutils"
brew "mpv"
brew "neovim"
brew "node"
brew "openssh"
brew "ripgrep"
brew "rust"
brew "stow"
brew "tailscale"
brew "the_silver_searcher"
brew "tmux"
brew "tmuxp"
brew "wget"

cask "1password"
cask "appcleaner"
cask "balenaetcher"
cask "discord"
cask "fantastical"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "gpg-suite"
cask "jdownloader"
cask "jetbrains-toolbox"
cask "keka"
cask "megasync"
cask "mimestream"
cask "netnewswire"
cask "nordvpn"
cask "notion"
cask "paintbrush"
cask "qbittorrent"
cask "raycast"
cask "rectangle"
cask "steam"
cask "visual-studio-code"
cask "vorta"
cask "yacreader"
cask "xld"
cask "zotero"

mas "Bear", id: 1091189122
mas "Things", id: 904280696
mas "Xcode", id: 497799835
